name: Clinicas API CI

on:
  push:
    branches:
      - main
      - "feature/**"
      - "fix/**"
      - "refactor/**"
      - "hotfix/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar o Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Rodar build e testes
        run: ./mvnw clean verify